services:
  - type: web
    name: whatsapp-webhook
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VERIFY_TOKEN
        generateValue: true
    healthCheckPath: /
